package com.example.themoviedb.person_details_screen.person_details_model

import com.example.themoviedb.person_details_screen.person_details_presenter.PersonDetailsPresenter

interface PersonDetailsModelInterface
